[package]

name = "ilc"
version = "0.0.1"
authors = ["Till Hoeppner <till@hoeppner.ws>"]

[dependencies]
regex = "*"
regex_macros = "*"
chrono = "*"
docopt = "*"
rustc-serialize = "*"
log = "*"
env_logger = "*"

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
