[package]
authors = ["Till Hoeppner <till@hoeppner.ws>"]
description = "IRC log converter/collector/cruncher"
homepage = "https://github.com/tilpner/ilc"
license = "Apache-2.0"
name = "ilc"
repository = "https://github.com/tilpner/ilc"
version = "0.1.1"

[[bin]]
doc = false
name = "ilc"

[dependencies]
bincode = "0.4.0"
blist = "0.0.4"
chrono = "0.2.18"
clap = "2.0.2"
env_logger = "0.3.2"
glob = "0.2.10"
log = "0.3.4"
regex = "0.1.46"
rmp = "0.7.3"
rmp-serialize = "0.7.0"
rustc-serialize = "0.3.16"

[profile.release]
debug = false
debug-assertions = false
lto = true
opt-level = 3
