[package]

name = "ilc"
version = "0.0.1"
license = "Apache-2.0"
authors = ["Till Hoeppner <till@hoeppner.ws>"]

[[bin]]
name = "ilc"
doc = false

[dependencies]
regex = "*"
regex_macros = "*"
chrono = "*"
docopt = "*"
rustc-serialize = "*"
log = "*"
env_logger = "*"
bincode = "*"
combine = "*"
glob = "*"

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
